package com.mycompany.bank;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mark2
 */
public class BankDataBaseImpl extends BankImpl implements DataBase {

    @Override
    public void save() {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Brak sterownika");
            e.printStackTrace();
            System.exit(1);
        }
        Connection conn = null;
        String strUrl = "jdbc:derby://localhost//1527/asdf";
        java.util.Properties props = new java.util.Properties();
        props.put("user", "root");
        props.put("password", "meaculpa");
        try {
            conn = (Connection) DriverManager.getConnection(strUrl, props);
            Statement statement = (Statement) conn.createStatement();
            statement.executeUpdate("create table app.client (\n"
                    + "Id Integer primary key GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "firstName varchar (50),\n"
                    + "lastName varchar (50),\n"
                    + "pesel varchar (11) unique,\n"
                    + "email varchar (50)\n"
                    + ")");
            statement.executeUpdate("create table app.account (\n"
                    + "Id Integer primary key GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "notes varchar (255),\n"
                    + "balance double,\n"
                    + "Id_client Integer constraint fk_client references app.client\n"
                    + ")");
            for (Account a : mAccounts) {
                statement.executeUpdate ("insert into app.client values ("
                        +a.id+","+a.name+",90051604117);");
            }
            conn.close();
        } catch (SQLException e) {
// TODO: handle exception
        }
    }

    @Override
    public void update() {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Brak sterownika");
            e.printStackTrace();
            System.exit(1);
        }
        Connection conn = null;
        String strUrl = "jdbc:derby://localhost//1527/asdf";
        java.util.Properties props = new java.util.Properties();
        props.put("user", "root");
        props.put("password", "meaculpa");
        try {
            conn = (Connection) DriverManager.getConnection(strUrl, props);
            Statement statement = (Statement) conn.createStatement();
            ResultSet result = statement.executeQuery("select * from Employees");
            while (result.next()) {
                System.out.print(result.getLong("id"));
                System.out.print(result.getLong("age"));
                System.out.print(result.getString("first"));
                System.out.println(result.getString("last"));
            }
            conn.close();
        } catch (SQLException e) {
// TODO: handle exception
        }

    }

    @Override
    public void remove(Integer pesel) {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Brak sterownika");
            e.printStackTrace();
            System.exit(1);
        }
        Connection conn = null;
        String strUrl = "jdbc:derby://localhost//1527/asdf";
        java.util.Properties props = new java.util.Properties();
        props.put("user", "root");
        props.put("password", "meaculpa");
        try {
            conn = (Connection) DriverManager.getConnection(strUrl, props);
            Statement statement = (Statement) conn.createStatement();
            ResultSet result = statement.executeQuery("delete from * from app.customer");
            conn.close();
        } catch (SQLException e) {
// TODO: handle exception
        }
    }

    @Override
    public void find(Integer pesel) {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Brak sterownika");
            e.printStackTrace();
            System.exit(1);
        }
        Connection conn = null;
        String strUrl = "jdbc:derby://localhost//1527/asdf";
        java.util.Properties props = new java.util.Properties();
        props.put("user", "root");
        props.put("password", "meaculpa");
        try {
            conn = (Connection) DriverManager.getConnection(strUrl, props);
            Statement statement = (Statement) conn.createStatement();
            ResultSet result = statement.executeQuery("select * from Employees");
            while (result.next()) {
                System.out.print(result.getLong("id"));
                System.out.print(result.getLong("age"));
                System.out.print(result.getString("first"));
                System.out.println(result.getString("last"));
            }
            conn.close();
        } catch (SQLException e) {
// TODO: handle exception
        }
    }
    
    public static void main (String [] args) {
        BankDataBaseImpl bank = new BankDataBaseImpl();
        bank.update ();
        bank.createAccount("Mark", "Warsaw");
        bank.createAccount("Moby", "Warsaw");
        bank.save ();
        
        System.out.println("All done");
    }
    
}
