/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanekGlowny.java
 *
 * Created on 2010-05-10, 20:51:32
 */

package program;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.net.ssl.SSLEngineResult.Status;
import javax.print.DocFlavor.READER;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdesktop.application.FrameView;

/**
 *
 * @author Piotrek
 */
public class PanelGlowny extends javax.swing.JFrame {

    /** Creates new form PanekGlowny */
    public PanelGlowny() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNick = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDodajPrzedmiot = new javax.swing.JButton();
        jEdytujPrzedmiot = new javax.swing.JButton();
        jUsunPrzedmiot = new javax.swing.JButton();
        jDodajPytanie = new javax.swing.JButton();
        jEdytujPytanie = new javax.swing.JButton();
        jUsunPytanie = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jIloscPytan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jZapiszJako = new javax.swing.JTextField();
        jLosujTest = new javax.swing.JButton();
        jNazwaPrzedmiotu = new javax.swing.JTextField();
        jTrescPytania = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaPrzedmiotow = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaPytan = new javax.swing.JList();
        jComboBoxPrzedmiotow = new javax.swing.JComboBox();
        jJakiPrzedmiot = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        otworzPlik = new javax.swing.JMenuItem();
        zapiszPlik = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(program.ProgramApp.class).getContext().getResourceMap(PanelGlowny.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jNick.setText(resourceMap.getString("jNick.text")); // NOI18N
        jNick.setName("jNick"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNick, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(308, 308, 308))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNick, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jDodajPrzedmiot.setText(resourceMap.getString("jDodajPrzedmiot.text")); // NOI18N
        jDodajPrzedmiot.setName("jDodajPrzedmiot"); // NOI18N
        jDodajPrzedmiot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajPrzedmiotActionPerformed(evt);
            }
        });

        jEdytujPrzedmiot.setText(resourceMap.getString("jEdytujPrzedmiot.text")); // NOI18N
        jEdytujPrzedmiot.setName("jEdytujPrzedmiot"); // NOI18N
        jEdytujPrzedmiot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdytujPrzedmiotActionPerformed(evt);
            }
        });

        jUsunPrzedmiot.setText(resourceMap.getString("jUsunPrzedmiot.text")); // NOI18N
        jUsunPrzedmiot.setName("jUsunPrzedmiot"); // NOI18N
        jUsunPrzedmiot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsunPrzedmiotActionPerformed(evt);
            }
        });

        jDodajPytanie.setText(resourceMap.getString("jDodajPytanie.text")); // NOI18N
        jDodajPytanie.setName("jDodajPytanie"); // NOI18N
        jDodajPytanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajPytanieActionPerformed(evt);
            }
        });

        jEdytujPytanie.setText(resourceMap.getString("jEdytujPytanie.text")); // NOI18N
        jEdytujPytanie.setName("jEdytujPytanie"); // NOI18N
        jEdytujPytanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdytujPytanieActionPerformed(evt);
            }
        });

        jUsunPytanie.setText(resourceMap.getString("jUsunPytanie.text")); // NOI18N
        jUsunPytanie.setName("jUsunPytanie"); // NOI18N
        jUsunPytanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsunPytanieActionPerformed(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jIloscPytan.setText(resourceMap.getString("jIloscPytan.text")); // NOI18N
        jIloscPytan.setName("jIloscPytan"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jZapiszJako.setText(resourceMap.getString("jZapiszJako.text")); // NOI18N
        jZapiszJako.setName("jZapiszJako"); // NOI18N

        jLosujTest.setBackground(resourceMap.getColor("jLosujTest.background")); // NOI18N
        jLosujTest.setFont(resourceMap.getFont("jLosujTest.font")); // NOI18N
        jLosujTest.setText(resourceMap.getString("jLosujTest.text")); // NOI18N
        jLosujTest.setName("jLosujTest"); // NOI18N
        jLosujTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLosujTestActionPerformed(evt);
            }
        });

        jNazwaPrzedmiotu.setText(resourceMap.getString("jNazwaPrzedmiotu.text")); // NOI18N
        jNazwaPrzedmiotu.setName("jNazwaPrzedmiotu"); // NOI18N
        jNazwaPrzedmiotu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jNazwaPrzedmiotuMousePressed(evt);
            }
        });

        jTrescPytania.setText(resourceMap.getString("jTrescPytania.text")); // NOI18N
        jTrescPytania.setEnabled(false);
        jTrescPytania.setName("jTrescPytania"); // NOI18N
        jTrescPytania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTrescPytaniaMousePressed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jListaPrzedmiotow.setName("jListaPrzedmiotow"); // NOI18N
        jListaPrzedmiotow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListaPrzedmiotowMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListaPrzedmiotow);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jListaPytan.setName("jListaPytan"); // NOI18N
        jScrollPane2.setViewportView(jListaPytan);

        jComboBoxPrzedmiotow.setName("jComboBoxPrzedmiotow"); // NOI18N
        jComboBoxPrzedmiotow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrzedmiotowActionPerformed(evt);
            }
        });

        jJakiPrzedmiot.setText(resourceMap.getString("jJakiPrzedmiot.text")); // NOI18N
        jJakiPrzedmiot.setName("jJakiPrzedmiot"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jDodajPrzedmiot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEdytujPrzedmiot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUsunPrzedmiot))
                            .addComponent(jNazwaPrzedmiotu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jDodajPytanie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEdytujPytanie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUsunPytanie))
                            .addComponent(jLabel5)
                            .addComponent(jTrescPytania, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLosujTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxPrzedmiotow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jJakiPrzedmiot))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jIloscPytan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jZapiszJako, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNazwaPrzedmiotu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrescPytania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDodajPrzedmiot)
                    .addComponent(jEdytujPrzedmiot)
                    .addComponent(jUsunPrzedmiot)
                    .addComponent(jDodajPytanie)
                    .addComponent(jEdytujPytanie)
                    .addComponent(jUsunPytanie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxPrzedmiotow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJakiPrzedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jIloscPytan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jZapiszJako, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLosujTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        otworzPlik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        otworzPlik.setText(resourceMap.getString("otworzPlik.text")); // NOI18N
        otworzPlik.setName("otworzPlik"); // NOI18N
        otworzPlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otworzPlikActionPerformed(evt);
            }
        });
        jMenu1.add(otworzPlik);

        zapiszPlik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        zapiszPlik.setText(resourceMap.getString("zapiszPlik.text")); // NOI18N
        zapiszPlik.setName("zapiszPlik"); // NOI18N
        zapiszPlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszPlikActionPerformed(evt);
            }
        });
        jMenu1.add(zapiszPlik);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(program.ProgramApp.class).getContext().getActionMap(PanelGlowny.class, this);
        jMenuItem2.setAction(actionMap.get("quit")); // NOI18N
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDodajPrzedmiotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajPrzedmiotActionPerformed
        Logger logger = new Logger();
        String nPrzedmiotu = jNazwaPrzedmiotu.getText();
        if(!przedmioty2pytan.containsKey(nPrzedmiotu)){ //sprawdzam czy nie ma przedmiotu w bazie i dodaje przedmiot do bazy
            Set<String> questions=new HashSet<String>();

            if(nPrzedmiotu.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Wpisz nazwę przedmiotu !", "Błąd użytkownika!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            logger.loggerBlad(4);
            przedmioty2pytan.put(nPrzedmiotu, questions);
            odswiezListePrzedmiotow();
            
            return;
        }else{  // gdy jest juz przedmiot o takiej nazwie
                JOptionPane.showMessageDialog(rootPane, "Jest już taka nazwa przedmiotu !", "Błąd użytkownika!", JOptionPane.ERROR_MESSAGE);
                return;
        }
    }//GEN-LAST:event_jDodajPrzedmiotActionPerformed

    private void jNazwaPrzedmiotuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNazwaPrzedmiotuMousePressed
        jNazwaPrzedmiotu.setText("");
    }//GEN-LAST:event_jNazwaPrzedmiotuMousePressed

    private void jTrescPytaniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTrescPytaniaMousePressed
        if(jTrescPytania.isEnabled())
            jTrescPytania.setText("");
    }//GEN-LAST:event_jTrescPytaniaMousePressed

    private void jListaPrzedmiotowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaPrzedmiotowMousePressed
        if(!jListaPrzedmiotow.isSelectionEmpty()){
            jTrescPytania.setEnabled(true);

            WybranyPrzedmiot=(String)jListaPrzedmiotow.getSelectedValue(); // metoda getSelectedValue - zwraa wybrane pole
            pytanias=przedmioty2pytan.get(WybranyPrzedmiot);
            odswiezListePytan();
        }else{  // gdy lista przedmiotow jest pusta
                JOptionPane.showMessageDialog(rootPane, "Nie możesz wykonać żadnej operacji! Na liście brak przedmiotów!", "Lista przedmiotów", JOptionPane.ERROR_MESSAGE);
                return;
        }
    }//GEN-LAST:event_jListaPrzedmiotowMousePressed

    private void jDodajPytanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajPytanieActionPerformed
        Logger logger = new Logger();
        if(pytanias==null){
            return;
        }
        String Pytanie = jTrescPytania.getText();
        if(Pytanie.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Wpisz treść pytania !", "Błąd użytkownika!", JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(pytanias.contains(Pytanie)){ // jesli jest juz takie pytanie w bazie
            JOptionPane.showMessageDialog(rootPane, "W bazie przedmiotu znajduje się już identyczne pytanie  !", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }
        logger.loggerBlad(5);
        pytanias.add(Pytanie);
        odswiezListePytan();
    }//GEN-LAST:event_jDodajPytanieActionPerformed

    private void jUsunPrzedmiotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsunPrzedmiotActionPerformed
        Logger logger = new Logger();
        if(!jListaPrzedmiotow.isSelectionEmpty()){ //jesli zaznaczono przedmiot
            przedmioty2pytan.remove(jListaPrzedmiotow.getSelectedValue());
            pytanias=null;
            logger.loggerBlad(6);
            odswiezListePrzedmiotow();
            odswiezListePytan();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Zaznacz przedmiot do usunięcia!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jUsunPrzedmiotActionPerformed

    private void jUsunPytanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsunPytanieActionPerformed
        Logger logger = new Logger();
        if(pytanias==null) return;

        if(!jListaPytan.isSelectionEmpty()){
            logger.loggerBlad(7);
            pytanias.remove(jListaPytan.getSelectedValue());
            odswiezListePytan();
        }else{
              JOptionPane.showMessageDialog(rootPane, "Zaznacz pytanie do usunięcia!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jUsunPytanieActionPerformed

    private void otworzPlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otworzPlikActionPerformed
        //skorzystalem ze skryptu Pana jStara z programu wykładowego + dodałem obsługę tylko na pliki tekstowe
        Logger logger = new Logger();
        logger.loggerBlad(8);
        JFileChooser fc=new JFileChooser();
        javax.swing.filechooser.FileFilter filter=new FileNameExtensionFilter("txt files", "txt");
        fc.addChoosableFileFilter(filter);
        File f;
        try{
            f=new File(new File("./").getCanonicalPath());
            fc.setCurrentDirectory(f);
        }catch(IOException e){
            e.printStackTrace();
        }
        int ret=fc.showDialog(null,"Otwórz bazę przedmiotów");
        if(ret==JFileChooser.APPROVE_OPTION){
            File file=fc.getSelectedFile();
            try{
                BufferedReader reader=new BufferedReader(new FileReader(file));
                String line;
                String lastSubject=null;
                przedmioty2pytan.clear();
                while((line=reader.readLine())!=null){
                    if(line.charAt(0)!='\t'){ // przedmiot
                        lastSubject=line;
                        pytanias=new HashSet<String>();
                        przedmioty2pytan.put(lastSubject, pytanias);
                    }else if(lastSubject!=null){ // pytanie
                        String line2=line.substring(1);
                        pytanias.add(line2);
                    }
                }
                odswiezListePrzedmiotow();
            }catch(FileNotFoundException e){
            }catch(IOException e1){}
        }
    }//GEN-LAST:event_otworzPlikActionPerformed

    private void zapiszPlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszPlikActionPerformed
        Logger logger = new Logger();
        logger.loggerBlad(9);
        JFileChooser fc=new JFileChooser();
        javax.swing.filechooser.FileFilter filter=new FileNameExtensionFilter("txt files", "txt");
        fc.addChoosableFileFilter(filter);
        File f;
        try{
            f=new File(new File("./").getCanonicalPath());
            fc.setCurrentDirectory(f);
        }catch(IOException e){
            e.printStackTrace();
        }
        int ret=fc.showSaveDialog(null);
        if(ret==JFileChooser.APPROVE_OPTION){
            File file=fc.getSelectedFile();
            FileOutputStream out;
            try{
                out=new FileOutputStream(file);
                BufferedOutputStream bout=new BufferedOutputStream(out);
                StringBuffer sb=new StringBuffer();
                for(String subject:przedmioty2pytan.keySet()){
                    sb.append(subject);
                    sb.append('\r');
                    sb.append('\n');
                    for(String question:przedmioty2pytan.get(subject)){
                        sb.append('\t');
                        sb.append(question);
                        sb.append('\r');
                        sb.append('\n');
                    }
                }
                bout.write(sb.toString().getBytes());
                bout.flush();
            }catch(FileNotFoundException e){
            }catch(IOException e1){}
        }
    }//GEN-LAST:event_zapiszPlikActionPerformed

    private void jEdytujPrzedmiotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdytujPrzedmiotActionPerformed
        // TODO add your handling code here:
        Logger logger = new Logger();
        if(jListaPrzedmiotow.isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Zaznacz przedmiot do edytowania!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nazwaPrzedmiotu = jNazwaPrzedmiotu.getText();
        if(przedmioty2pytan.containsKey(nazwaPrzedmiotu)){ // juz jest taki
            JOptionPane.showMessageDialog(rootPane, "Jest już taki przedmiot!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        if(nazwaPrzedmiotu.equals("")){                     // puste pole w nazwie przedmiotu
            JOptionPane.showMessageDialog(rootPane, "Puste pole w nazwie przedmiotu!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }
        logger.loggerBlad(10);
        pytanias = przedmioty2pytan.remove(WybranyPrzedmiot);
        WybranyPrzedmiot = nazwaPrzedmiotu;
        przedmioty2pytan.put(nazwaPrzedmiotu, pytanias);

        odswiezListePrzedmiotow();
        odswiezListePytan();
    }//GEN-LAST:event_jEdytujPrzedmiotActionPerformed

    private void jEdytujPytanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdytujPytanieActionPerformed
        // TODO add your handling code here:
        Logger logger = new Logger();
        if(jListaPytan.isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Zaznacz pytanie do edytowania!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String Pytanie = jTrescPytania.getText();
        if(Pytanie.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Wpisz treść pytania !", "Błąd użytkownika!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(pytanias.contains(Pytanie)){ // jesli jest juz takie pytanie w bazie
            JOptionPane.showMessageDialog(rootPane, "W bazie jest już identyczne pytanie  !", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }
        logger.loggerBlad(11);
        pytanias.remove(jListaPytan.getSelectedValue());
        pytanias.add(Pytanie);
        odswiezListePytan();
    }//GEN-LAST:event_jEdytujPytanieActionPerformed

    private void jComboBoxPrzedmiotowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrzedmiotowActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String petName = (String)cb.getSelectedItem();
        //Array petStrings = { "A","B","C","D"};
        jComboBoxPrzedmiotow.setSelectedIndex(1);
        jComboBoxPrzedmiotow.addItem("asdas");
        //jComboBoxPrzedmiotow.addActionListener(petStrings);
    }//GEN-LAST:event_jComboBoxPrzedmiotowActionPerformed

    private void jLosujTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLosujTestActionPerformed
        // TODO add your handling code here:
        String jaki_przedmiot = jJakiPrzedmiot.getText();
        String ilosc_pytan = jIloscPytan.getText();
        String zapisz_jako = jZapiszJako.getText();
        int x = Integer.parseInt(ilosc_pytan);

        if( !przedmioty2pytan.containsKey(jaki_przedmiot) ){
            JOptionPane.showMessageDialog(rootPane, "Podany przedmiot: \'" + jaki_przedmiot + "\' nie istnieje w bazie!", "Błąd użytkownika", JOptionPane.ERROR_MESSAGE);
            return;
        }

        /*ArrayList<String> pytaniaDoEgzaminu = new ArrayList<String>();
        for(Set<String> pytanka:przedmioty2pytan.values()){
            pytaniaDoEgzaminu.addAll(pytanka);
        }*/

        zapiszPlik(zapisz_jako);

        JOptionPane.showMessageDialog(rootPane, "Przedmiot \'" + jaki_przedmiot + "\'. Ilość losowanych pytań: " + x, "Info", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLosujTestActionPerformed

    public void zapiszPlik(String nazwa_pliku){
        File file = new File(nazwa_pliku);
        try{
            if(file.createNewFile()){
                //utworzono plik
            }else{
                //nie utworzono
            }
        }
        catch(IOException e){
            // blad wyjscia
        }

    }

    private void odswiezListePrzedmiotow(){
        jListaPrzedmiotow.setListData((String[])przedmioty2pytan.keySet().toArray(new String[0]));
        /* zbior wszystkich przedmiotow
        ArrayList<String> pytaniaDoEgzaminu=new ArrayList<String>();
        for(Set<String> pytanias:przedmioty2pytan.values()){
            pytaniaDoEgzaminu.addAll(pytanias);
        }*/
    }

    private void odswiezListePytan(){
        if(pytanias==null){
            jListaPytan.setListData(new Object[0]);
            return;
        }
        jListaPytan.setListData((String[])pytanias.toArray(new String[0]));
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelGlowny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxPrzedmiotow;
    private javax.swing.JButton jDodajPrzedmiot;
    private javax.swing.JButton jDodajPytanie;
    private javax.swing.JButton jEdytujPrzedmiot;
    private javax.swing.JButton jEdytujPytanie;
    private javax.swing.JTextField jIloscPytan;
    private javax.swing.JTextField jJakiPrzedmiot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListaPrzedmiotow;
    private javax.swing.JList jListaPytan;
    private javax.swing.JButton jLosujTest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jNazwaPrzedmiotu;
    private javax.swing.JLabel jNick;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTrescPytania;
    private javax.swing.JButton jUsunPrzedmiot;
    private javax.swing.JButton jUsunPytanie;
    private javax.swing.JTextField jZapiszJako;
    private javax.swing.JMenuItem otworzPlik;
    private javax.swing.JMenuItem zapiszPlik;
    // End of variables declaration//GEN-END:variables

    private final Map<String,Set<String>> przedmioty2pytan = new HashMap<String, Set<String>>();
    private Set<String> pytanias=null;
    private String WybranyPrzedmiot=null;
}
